import type { Application } from '../types';

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    company: 'Stripe',
    role: 'Senior Software Engineer — Payments Infrastructure',
    appliedDate: new Date(Date.now() - 45 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 45 * 86400000).toISOString(),
    status: 'ghosted',
    emailSnippet: 'Thank you for applying to Stripe! We have received your application for the Senior Software Engineer role...',
    domain: 'stripe.com',
    daysSinceApplied: 45,
    daysSinceActivity: 45,
    isGhosted: true,
    ghostedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: '2',
    company: 'Linear',
    role: 'Product Engineer — Core Experience',
    appliedDate: new Date(Date.now() - 12 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'interviewing',
    emailSnippet: 'Hi! We loved your background and would like to schedule a technical interview. Are you available next week?',
    domain: 'linear.app',
    daysSinceApplied: 12,
    daysSinceActivity: 3,
    isGhosted: false,
  },
  {
    id: '3',
    company: 'Vercel',
    role: 'Software Engineer — Developer Experience',
    appliedDate: new Date(Date.now() - 38 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 38 * 86400000).toISOString(),
    status: 'ghosted',
    emailSnippet: 'Thank you for your application to Vercel. We will review your profile and be in touch.',
    domain: 'vercel.com',
    daysSinceApplied: 38,
    daysSinceActivity: 38,
    isGhosted: true,
    ghostedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: '4',
    company: 'Notion',
    role: 'Full Stack Engineer',
    appliedDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: 'screening',
    emailSnippet: 'We would love to schedule a 30-minute phone screen to learn more about your experience.',
    domain: 'notion.so',
    daysSinceApplied: 5,
    daysSinceActivity: 4,
    isGhosted: false,
  },
  {
    id: '5',
    company: 'Anthropic',
    role: 'Software Engineer — Claude Integrations',
    appliedDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'applied',
    emailSnippet: 'Application received! Thank you for applying to Anthropic. We have received your application for...',
    domain: 'anthropic.com',
    daysSinceApplied: 2,
    daysSinceActivity: 2,
    isGhosted: false,
  },
  {
    id: '6',
    company: 'Figma',
    role: 'Engineering Manager — Platform',
    appliedDate: new Date(Date.now() - 60 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 55 * 86400000).toISOString(),
    status: 'rejected',
    emailSnippet: 'After careful consideration, we have decided to move forward with other candidates whose experience more closely aligns...',
    domain: 'figma.com',
    daysSinceApplied: 60,
    daysSinceActivity: 55,
    isGhosted: false,
  },
  {
    id: '7',
    company: 'Loom',
    role: 'Frontend Engineer',
    appliedDate: new Date(Date.now() - 8 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 8 * 86400000).toISOString(),
    status: 'applied',
    emailSnippet: 'We have received your application and will be in touch if your background is a match for our needs.',
    domain: 'loom.com',
    daysSinceApplied: 8,
    daysSinceActivity: 8,
    isGhosted: false,
  },
  {
    id: '8',
    company: 'Retool',
    role: 'Software Engineer — Backend',
    appliedDate: new Date(Date.now() - 20 * 86400000).toISOString(),
    lastActivityDate: new Date(Date.now() - 20 * 86400000).toISOString(),
    status: 'applied',
    emailSnippet: 'Thanks for applying to Retool! Your application for Software Engineer Backend has been received.',
    domain: 'retool.com',
    daysSinceApplied: 20,
    daysSinceActivity: 20,
    isGhosted: false,
  },
];
